// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psvoutlfzriucoouwyyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzdm91dGxmenJpdWNvb3V3eXlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MjE1NjIsImV4cCI6MjA2MTA5NzU2Mn0.ztcBwYMhzgsNKXVFHHZKdHSViWT5g161y7eNtUNlKxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);